import { ExternalLink, FileClock, Pencil, Plus, Search, Trash2, X } from 'lucide-react'
import { useMemo, useState } from 'react'; import { STAGES, type AlertFilter, type ApplicationRecord } from '../types'; import { alertLevel, formatDate, matchesAlert, REJECTED_STAGES, silentDays } from '../lib/radar'; import { Badge, Button, IconButton } from './ui/Button'; import { Card } from './ui/Card'; import { Input, Select } from './ui/Field'
const stageTone = (r: ApplicationRecord) => REJECTED_STAGES.includes(r.stage) || r.stage === '已撤回' ? 'neutral' : ['Offer', '意向'].includes(r.stage) ? 'teal' : r.stage === '待投递' ? 'blue' : 'amber'
export function ApplicationList({ records, onAdd, onEdit, onTimeline, onDelete }: { records: ApplicationRecord[]; onAdd: () => void; onEdit: (r: ApplicationRecord) => void; onTimeline: (r: ApplicationRecord) => void; onDelete: (r: ApplicationRecord) => void }) {
  const [query, setQuery] = useState(''); const [stage, setStage] = useState('全部'); const [platform, setPlatform] = useState('全部'); const [alert, setAlert] = useState<AlertFilter>('全部'); const platforms = [...new Set(records.map(r => r.platform))]
  const filtered = useMemo(() => records.filter(r => `${r.company} ${r.role} ${r.notes}`.toLowerCase().includes(query.toLowerCase()) && (stage === '全部' || r.stage === stage) && (platform === '全部' || r.platform === platform) && matchesAlert(r, alert)), [records, query, stage, platform, alert]); const hasFilters = !!query || stage !== '全部' || platform !== '全部' || alert !== '全部'
  const alertBadge = (r: ApplicationRecord) => { const level = alertLevel(r); return level === '14天+' ? <Badge tone="red">沉默 {silentDays(r)} 天</Badge> : level === '7天+' ? <Badge tone="amber">待跟进 {silentDays(r)} 天</Badge> : level === '待投递' ? <Badge tone="blue">待投递</Badge> : level === '已结束' ? <Badge>已结束</Badge> : <span className="text-xs text-slate-400">正常</span> }
  const clear = () => { setQuery(''); setStage('全部'); setPlatform('全部'); setAlert('全部') }
  return <div className="space-y-4 animate-rise"><div className="flex items-end justify-between gap-3"><div><h1 className="text-xl font-semibold sm:text-2xl">投递记录</h1><p className="mt-1 text-sm text-slate-500">{filtered.length === records.length ? `共 ${records.length} 条记录` : `显示 ${filtered.length} / ${records.length} 条`}</p></div><Button onClick={onAdd} className="hidden sm:inline-flex"><Plus size={16}/>新增投递</Button></div>
    <Card className="p-3"><div className="grid gap-2 md:grid-cols-[minmax(240px,1fr)_140px_140px_130px_auto]"><div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={16}/><Input className="pl-9" value={query} onChange={e => setQuery(e.target.value)} placeholder="搜索公司、岗位或备注"/></div><Select value={stage} onChange={e => setStage(e.target.value)} aria-label="阶段"><option>全部</option>{STAGES.map(s => <option key={s}>{s}</option>)}</Select><Select value={platform} onChange={e => setPlatform(e.target.value)} aria-label="平台"><option>全部</option>{platforms.map(p => <option key={p}>{p}</option>)}</Select><Select value={alert} onChange={e => setAlert(e.target.value as AlertFilter)} aria-label="预警"><option>全部</option><option>正常</option><option>7天+</option><option>14天+</option></Select>{hasFilters && <Button variant="ghost" onClick={clear}><X size={15}/>清除</Button>}</div></Card>
    {!filtered.length ? <Card className="grid min-h-64 place-items-center p-8 text-center"><div><Search className="mx-auto mb-3 text-slate-300" size={30}/><h3 className="font-medium">没有匹配的记录</h3><p className="mt-1 text-sm text-slate-500">调整筛选条件，或新增一条投递。</p></div></Card> : <><div className="hidden overflow-hidden rounded-lg border border-slate-200 bg-white lg:block"><table className="w-full table-fixed text-left text-sm"><thead className="border-b border-slate-200 bg-slate-50 text-xs text-slate-500"><tr><th className="w-[30%] px-4 py-2.5 font-medium">公司 / 岗位</th><th className="w-[13%] px-4 py-2.5 font-medium">平台</th><th className="w-[12%] px-4 py-2.5 font-medium">阶段</th><th className="w-[14%] px-4 py-2.5 font-medium">行动状态</th><th className="w-[20%] px-4 py-2.5 font-medium">时间</th><th className="w-[11%] px-4 py-2.5 text-right font-medium">操作</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map(r => <tr key={r.id} className="h-[68px] hover:bg-slate-50"><td className="px-4 py-2"><div className="flex items-center gap-2"><p className="truncate font-medium">{r.company}</p>{r.isSample && <Badge tone="blue">示例</Badge>}</div><p className="mt-1 truncate text-xs text-slate-500">{r.role}</p></td><td className="truncate px-4 py-2 text-slate-600" title={r.platform}>{r.platform}</td><td className="px-4 py-2"><Badge tone={stageTone(r)}>{r.stage}</Badge></td><td className="px-4 py-2">{alertBadge(r)}</td><td className="px-4 py-2 text-xs text-slate-500"><p>投递 {formatDate(r.appliedAt, false, '尚未投递')}</p><p className="mt-1">更新 {formatDate(r.updatedAt)}</p></td><td className="px-4 py-2"><div className="flex justify-end"><IconButton title="查看时间线" aria-label="查看时间线" onClick={() => onTimeline(r)}><FileClock size={16}/></IconButton><IconButton title="编辑" aria-label="编辑" onClick={() => onEdit(r)}><Pencil size={16}/></IconButton><IconButton title="删除" aria-label="删除" onClick={() => onDelete(r)}><Trash2 size={16}/></IconButton></div></td></tr>)}</tbody></table></div>
      <div className="grid gap-2 lg:hidden">{filtered.map(r => <Card key={r.id} className="p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h3 className="truncate font-medium">{r.company}</h3><p className="mt-1 truncate text-sm text-slate-500">{r.role}</p></div><Badge tone={stageTone(r)}>{r.stage}</Badge></div><div className="mt-3 flex flex-wrap items-center gap-2">{alertBadge(r)}<span className="text-xs text-slate-400">{r.platform}</span></div><div className="mt-3 flex items-center justify-between border-t border-slate-100 pt-2 text-xs text-slate-400"><span>更新 {formatDate(r.updatedAt)}</span><div className="flex"><IconButton onClick={() => onTimeline(r)} aria-label="时间线"><FileClock size={16}/></IconButton>{r.url && <a aria-label="打开投递链接" className="grid size-9 place-items-center rounded-md hover:bg-slate-100" href={r.url} target="_blank" rel="noreferrer"><ExternalLink size={16}/></a>}<IconButton onClick={() => onEdit(r)} aria-label="编辑"><Pencil size={16}/></IconButton><IconButton onClick={() => onDelete(r)} aria-label="删除"><Trash2 size={16}/></IconButton></div></div></Card>)}</div></>}</div>
}
