import { ExternalLink, FileClock, MoreHorizontal, Pencil, Search, Trash2 } from 'lucide-react'
import { useMemo, useState } from 'react'
import { STAGES, type AlertFilter, type ApplicationRecord } from '../types'
import { alertLevel, formatDate, matchesAlert, silentDays } from '../lib/radar'
import { Badge, Button, IconButton } from './ui/Button'
import { Card } from './ui/Card'
import { Input, Select } from './ui/Field'

export function ApplicationList({ records, onAdd, onEdit, onTimeline, onDelete }: { records: ApplicationRecord[]; onAdd: () => void; onEdit: (r: ApplicationRecord) => void; onTimeline: (r: ApplicationRecord) => void; onDelete: (r: ApplicationRecord) => void }) {
  const [query, setQuery] = useState(''); const [stage, setStage] = useState('全部'); const [platform, setPlatform] = useState('全部'); const [alert, setAlert] = useState<AlertFilter>('全部')
  const platforms = [...new Set(records.map(r => r.platform))]
  const filtered = useMemo(() => records.filter(r => `${r.company} ${r.role} ${r.notes}`.toLowerCase().includes(query.toLowerCase()) && (stage === '全部' || r.stage === stage) && (platform === '全部' || r.platform === platform) && matchesAlert(r, alert)), [records, query, stage, platform, alert])
  const alertBadge = (r: ApplicationRecord) => { const level = alertLevel(r); return level === '14天+' ? <Badge tone="red">沉默 {silentDays(r)} 天</Badge> : level === '7天+' ? <Badge tone="amber">待跟进 {silentDays(r)} 天</Badge> : level === '已结束' ? <Badge>{level}</Badge> : <Badge tone="teal">正常</Badge> }
  return <div className="space-y-5 animate-rise">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-widest text-amber">投递档案</p><h2 className="mt-1 text-2xl font-extrabold text-ink">共 {records.length} 条投递记录</h2></div><Button onClick={onAdd}>新增投递</Button></div>
    <Card className="p-3"><div className="grid gap-2 md:grid-cols-[minmax(15rem,1fr)_10rem_10rem_9rem]"><div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-stone-400" size={17}/><Input className="pl-9" value={query} onChange={e => setQuery(e.target.value)} placeholder="搜索公司、岗位或备注" /></div><Select value={stage} onChange={e => setStage(e.target.value)}><option>全部</option>{STAGES.map(s => <option key={s}>{s}</option>)}</Select><Select value={platform} onChange={e => setPlatform(e.target.value)}><option>全部</option>{platforms.map(p => <option key={p}>{p}</option>)}</Select><Select value={alert} onChange={e => setAlert(e.target.value as AlertFilter)}><option>全部</option><option>正常</option><option>7天+</option><option>14天+</option></Select></div></Card>
    {!filtered.length ? <Card className="grid min-h-64 place-items-center p-8 text-center"><div><Search className="mx-auto mb-3 text-stone-300" size={34}/><h3 className="font-bold text-ink">没有匹配的记录</h3><p className="mt-1 text-sm text-stone-500">调整筛选条件，或新增一条真实投递。</p></div></Card> : <>
      <div className="hidden overflow-hidden rounded-lg border border-stone-200 bg-white shadow-sm lg:block"><table className="w-full table-fixed text-left text-sm"><thead className="bg-stone-50 text-xs uppercase tracking-wider text-stone-500"><tr><th className="w-[28%] px-4 py-3">公司 / 岗位</th><th className="w-[13%] px-4 py-3">平台</th><th className="w-[12%] px-4 py-3">阶段</th><th className="w-[17%] px-4 py-3">预警</th><th className="w-[20%] px-4 py-3">日期</th><th className="w-[10%] px-4 py-3 text-right">操作</th></tr></thead><tbody className="divide-y divide-stone-100">{filtered.map(r => <tr key={r.id} className="group transition hover:bg-orange-50/60"><td className="px-4 py-4"><div className="flex items-center gap-2"><p className="truncate font-bold text-ink">{r.company}</p>{r.isSample && <Badge tone="blue">示例</Badge>}</div><p className="mt-1 truncate text-stone-500">{r.role}</p></td><td className="truncate px-4 py-4 text-stone-600">{r.platform}</td><td className="px-4 py-4"><Badge tone={['Offer', '意向'].includes(r.stage) ? 'teal' : 'neutral'}>{r.stage}</Badge></td><td className="px-4 py-4">{alertBadge(r)}</td><td className="px-4 py-4 text-xs text-stone-500"><p>投递 {formatDate(r.appliedAt)}</p><p className="mt-1">检查 {formatDate(r.lastCheckedAt)}</p></td><td className="px-4 py-4"><div className="flex justify-end"><IconButton title="时间线" onClick={() => onTimeline(r)}><FileClock size={17}/></IconButton><IconButton title="编辑" onClick={() => onEdit(r)}><Pencil size={17}/></IconButton><IconButton title="删除" onClick={() => onDelete(r)}><Trash2 size={17}/></IconButton></div></td></tr>)}</tbody></table></div>
      <div className="grid gap-3 lg:hidden">{filtered.map(r => <Card key={r.id} className="p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="font-bold text-ink">{r.company}</h3>{r.isSample && <Badge tone="blue">示例</Badge>}</div><p className="mt-1 text-sm text-stone-600">{r.role}</p></div><IconButton onClick={() => onEdit(r)}><MoreHorizontal size={19}/></IconButton></div><div className="mt-4 flex flex-wrap gap-2"><Badge>{r.platform}</Badge><Badge tone="amber">{r.stage}</Badge>{alertBadge(r)}</div><div className="mt-4 flex items-center justify-between border-t border-stone-100 pt-3 text-xs text-stone-500"><span>检查：{formatDate(r.lastCheckedAt)}</span><div className="flex"><IconButton onClick={() => onTimeline(r)}><FileClock size={17}/></IconButton>{r.url && <a className="grid size-10 place-items-center rounded-md hover:bg-orange-50 hover:text-amber" href={r.url} target="_blank" rel="noreferrer"><ExternalLink size={17}/></a>}<IconButton onClick={() => onDelete(r)}><Trash2 size={17}/></IconButton></div></div></Card>)}</div>
    </>}
  </div>
}
