import { BarChart3, ClipboardCheck, Database, ListChecks, Plus, Radar } from 'lucide-react'
import type { AppMode } from '../config'
import { Button } from './ui/Button'
export type Page = 'overview' | 'records' | 'queue' | 'settings'
const nav = [{ id: 'overview' as const, label: '工作台', icon: BarChart3 }, { id: 'records' as const, label: '投递记录', icon: ListChecks }, { id: 'queue' as const, label: '行动队列', icon: ClipboardCheck }, { id: 'settings' as const, label: '数据管理', icon: Database }]
export function AppShell({ page, setPage, onAdd, queueCount, recordCount, mode, children }: { page: Page; setPage: (p: Page) => void; onAdd: () => void; queueCount: number; recordCount: number; mode: AppMode; children: React.ReactNode }) {
  return <div className="min-h-screen bg-slate-50 text-slate-900 lg:grid lg:grid-cols-[208px_minmax(0,1fr)]">
    <aside className="hidden border-r border-slate-200 bg-white lg:flex lg:min-h-screen lg:flex-col lg:sticky lg:top-0 lg:h-screen">
      <div className="flex h-16 items-center gap-2.5 border-b border-slate-100 px-5"><span className="grid size-8 place-items-center rounded-md bg-blue-600 text-white"><Radar size={18}/></span><div><p className="text-sm font-semibold">秋招雷达</p><p className="text-[11px] text-slate-400">投递工作台</p></div></div>
      <nav className="space-y-1 p-3" aria-label="主导航">{nav.map(item => <button key={item.id} onClick={() => setPage(item.id)} className={`flex h-10 w-full items-center gap-3 rounded-md px-3 text-sm font-medium transition ${page === item.id ? 'bg-blue-50 text-blue-700' : 'text-slate-600 hover:bg-slate-50 hover:text-slate-900'}`}><item.icon size={17}/><span>{item.label}</span>{item.id === 'queue' && queueCount > 0 && <span className="ml-auto rounded-full bg-blue-100 px-2 py-0.5 text-[11px] text-blue-700">{queueCount}</span>}</button>)}</nav>
      <div className="mt-auto border-t border-slate-100 p-4"><div className="rounded-md bg-slate-50 p-3"><div className="flex items-center justify-between text-xs"><span className="text-slate-500">数据状态</span><span className={`font-medium ${mode === 'personal' ? 'text-emerald-700' : 'text-blue-700'}`}>{mode === 'personal' ? '个人模式' : '演示模式'}</span></div><p className="mt-2 text-xs text-slate-500">当前浏览器 · {recordCount} 条</p></div></div>
    </aside>
    <div className="min-w-0"><header className="sticky top-0 z-30 border-b border-slate-200 bg-white/95 backdrop-blur"><div className="flex h-14 items-center gap-3 px-4 sm:px-6 lg:h-16 lg:px-8"><div className="flex items-center gap-2 lg:hidden"><span className="grid size-8 place-items-center rounded-md bg-blue-600 text-white"><Radar size={18}/></span><span className="text-sm font-semibold">秋招雷达</span></div><div className="hidden lg:block"><p className="text-sm font-semibold">{nav.find(n => n.id === page)?.label}</p><p className="text-xs text-slate-400">{mode === 'personal' ? '本地个人数据' : '虚构示例数据'} · {recordCount} 条记录</p></div><Button onClick={onAdd} className="ml-auto"><Plus size={16}/>新增投递</Button></div><nav className="flex overflow-x-auto px-2 lg:hidden" aria-label="移动端主导航">{nav.map(item => <button key={item.id} onClick={() => setPage(item.id)} className={`flex min-w-24 flex-1 items-center justify-center gap-1.5 border-b-2 px-2 py-2.5 text-xs font-medium ${page === item.id ? 'border-blue-600 text-blue-700' : 'border-transparent text-slate-500'}`}><item.icon size={15}/>{item.label}</button>)}</nav></header>
      <main className="mx-auto max-w-[1440px] p-4 sm:p-6 lg:p-8">{children}</main>
    </div>
  </div>
}
