import { AlertCircle, ArrowRight, BriefcaseBusiness, CalendarClock, CheckCircle2, Clock3, Inbox, Plus, Send, Trophy } from 'lucide-react'
import type { ApplicationRecord } from '../types'
import { ACTIVE_STAGES, alertLevel, daysUntilDeadline, formatDate, inspectionPriority, isDeadlineSoon } from '../lib/radar'
import { Button, Badge } from './ui/Button'; import { Card } from './ui/Card'; import type { Page } from './AppShell'; import { IS_PERSONAL } from '../config'
export function Dashboard({ records, setPage, onAdd }: { records: ApplicationRecord[]; setPage: (page: Page) => void; onAdd: () => void }) {
  const pending = records.filter(r => r.stage === '待投递').length; const active = records.filter(r => ACTIVE_STAGES.includes(r.stage)).length; const alerts = records.filter(r => ['7天+', '14天+'].includes(alertLevel(r))).length; const offers = records.filter(r => r.stage === 'Offer').length
  const actions = records.filter(r => r.stage === '待投递' || ['7天+', '14天+'].includes(alertLevel(r))).sort((a, b) => inspectionPriority(b) - inspectionPriority(a)).slice(0, 6)
  const recent = [...records].sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)).slice(0, 5)
  if (!records.length) return <div className="grid min-h-[68vh] place-items-center"><div className="max-w-md text-center animate-rise"><span className="mx-auto grid size-14 place-items-center rounded-lg border border-slate-200 bg-white text-blue-600"><Inbox size={26}/></span><h2 className="mt-5 text-2xl font-semibold tracking-tight">建立你的投递工作台</h2><p className="mt-2 text-sm leading-6 text-slate-500">{IS_PERSONAL ? '当前浏览器还没有投递记录。可以新增第一条，或从备份文件导入；个人模式不会自动加入示例数据。' : '演示数据已被清空。你可以新增虚构记录，继续体验完整流程。'}</p><div className="mt-6 flex justify-center gap-2"><Button onClick={onAdd}><Plus size={16}/>新增投递</Button><Button variant="secondary" onClick={() => setPage('settings')}>导入数据</Button></div></div></div>
  const stats = [{ label: '全部投递', value: records.length, icon: BriefcaseBusiness, tone: 'text-slate-700 bg-slate-100' }, { label: '进行中', value: active, icon: Send, tone: 'text-blue-700 bg-blue-50' }, { label: '待跟进 / 沉默', value: alerts, icon: AlertCircle, tone: 'text-orange-700 bg-orange-50' }, { label: '待投递', value: pending, icon: Clock3, tone: 'text-violet-700 bg-violet-50' }, { label: 'Offer', value: offers, icon: Trophy, tone: 'text-emerald-700 bg-emerald-50' }]
  return <div className="space-y-6 animate-rise"><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-xl font-semibold tracking-tight sm:text-2xl">今天先做什么</h1><p className="mt-1 text-sm text-slate-500">按截止时间与沉默天数，集中处理最需要行动的机会。</p></div>{actions.length > 0 && <Button variant="secondary" onClick={() => setPage('queue')}>查看全部行动 <ArrowRight size={16}/></Button>}</div>
    {records.some(r => r.isSample) && <div className="flex items-center gap-2 rounded-md border border-blue-200 bg-blue-50 px-3 py-2 text-xs text-blue-800"><Badge tone="blue">虚构示例</Badge><span>当前演示记录均为独立虚构数据，不含个人投递信息。</span></div>}
    <div className="grid grid-cols-2 gap-3 md:grid-cols-5">{stats.map(s => <Card key={s.label} className="p-4"><div className="flex items-start justify-between"><div><p className="text-xs text-slate-500">{s.label}</p><p className="mt-2 text-2xl font-semibold tabular-nums">{s.value}</p></div><span className={`grid size-8 place-items-center rounded-md ${s.tone}`}><s.icon size={17}/></span></div></Card>)}</div>
    <div className="grid gap-4 xl:grid-cols-[minmax(0,1.45fr)_minmax(320px,.55fr)]"><Card><div className="flex items-center justify-between border-b border-slate-100 px-4 py-3"><div><h2 className="text-sm font-semibold">行动队列</h2><p className="mt-0.5 text-xs text-slate-400">待投递、临近截止与长时间未更新</p></div><span className="text-xs text-slate-500">{actions.length} 项优先</span></div><div className="divide-y divide-slate-100">{actions.length ? actions.map(r => { const deadline = daysUntilDeadline(r); const urgent = isDeadlineSoon(r); const level = alertLevel(r); return <button key={r.id} onClick={() => setPage('queue')} className="grid w-full gap-2 px-4 py-3 text-left transition hover:bg-slate-50 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center"><div className="min-w-0"><p className="truncate text-sm font-medium">{r.company} <span className="font-normal text-slate-400">·</span> {r.role}</p><p className="mt-1 truncate text-xs text-slate-500">{r.stage} · {r.platform}</p></div><Badge tone={urgent || level === '14天+' ? 'red' : r.stage === '待投递' ? 'blue' : 'amber'}>{urgent ? (deadline! < 0 ? `已逾期 ${Math.abs(deadline!)} 天` : `${deadline} 天后截止`) : r.stage === '待投递' ? '等待投递' : `${level} 未更新`}</Badge></button> }) : <div className="px-4 py-12 text-center text-sm text-slate-500"><CheckCircle2 className="mx-auto mb-2 text-emerald-600"/>当前没有需要优先处理的事项</div>}</div></Card>
      <Card><div className="border-b border-slate-100 px-4 py-3"><h2 className="text-sm font-semibold">最近动态</h2><p className="mt-0.5 text-xs text-slate-400">按最后更新时间排序</p></div><div className="divide-y divide-slate-100">{recent.map(r => <button key={r.id} onClick={() => setPage('records')} className="flex w-full items-center gap-3 px-4 py-3 text-left hover:bg-slate-50"><span className="grid size-8 shrink-0 place-items-center rounded-md bg-slate-100 text-slate-500"><CalendarClock size={15}/></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{r.company} · {r.role}</p><p className="mt-0.5 text-xs text-slate-400">{r.stage} · {formatDate(r.updatedAt, true)}</p></div></button>)}</div></Card></div>
  </div>
}
