import { AlertTriangle, Bot, Database, Download, FileDown, FileJson, FileUp, LockKeyhole, Plug, Trash2, Upload } from 'lucide-react'
import { useRef, useState } from 'react'
import { parseCsv, csvTemplate, toCsv } from '../lib/csv'
import { createBackup, downloadText, parseBackup } from '../lib/storage'
import { STAGES, type ApplicationRecord, type CheckResult } from '../types'
import { Button, Badge } from './ui/Button'
import { Card, CardContent, CardHeader } from './ui/Card'
import { Dialog } from './ui/Dialog'

export function DataSettings({ records, onImport, onRestore, onClear, onCheckResult }: { records: ApplicationRecord[]; onImport: (r: ApplicationRecord[]) => void; onRestore: (r: ApplicationRecord[]) => void; onClear: () => void; onCheckResult: (r: CheckResult) => void }) {
  const [message, setMessage] = useState<{ tone: 'ok' | 'error'; text: string }>(); const [confirmClear, setConfirmClear] = useState(false)
  const csvRef = useRef<HTMLInputElement>(null); const jsonRef = useRef<HTMLInputElement>(null); const checkRef = useRef<HTMLInputElement>(null)
  const readFile = async (file: File | undefined, handler: (text: string) => void) => { if (!file) return; try { handler(await file.text()) } catch { setMessage({ tone: 'error', text: '文件读取失败，请重试。' }) } }
  const importCsv = (text: string) => { const result = parseCsv(text); if (result.errors.length) { setMessage({ tone: 'error', text: `${result.errors.slice(0, 3).join('；')}${result.errors.length > 3 ? `；另有 ${result.errors.length - 3} 条错误` : ''}` }); return } onImport(result.records); setMessage({ tone: 'ok', text: `已导入 ${result.records.length} 条记录。` }) }
  const restore = (text: string) => { try { const data = parseBackup(text); onRestore(data); setMessage({ tone: 'ok', text: `已恢复 ${data.length} 条记录。` }) } catch (e) { setMessage({ tone: 'error', text: e instanceof Error ? e.message : '备份文件无效' }) } }
  const importCheck = (text: string) => { try { const data = JSON.parse(text) as CheckResult; if (data.schemaVersion !== '1.0' || !data.connectorId || !data.checkedAt || !['changed', 'unchanged', 'needs_review', 'error'].includes(data.status)) throw new Error('检查结果缺少必填字段或版本不受支持'); if (data.stage && !STAGES.includes(data.stage)) throw new Error('检查结果中的阶段无效'); onCheckResult(data); setMessage({ tone: 'ok', text: '检查结果已导入并写入记录历史。' }) } catch (e) { setMessage({ tone: 'error', text: e instanceof Error ? e.message : '检查结果 JSON 无效' }) } }
  const sections = [
    { icon: FileDown, title: 'CSV 表格', desc: '批量迁移或编辑投递数据。导入前会校验字段、阶段和日期。', actions: <><Button variant="secondary" onClick={() => downloadText('秋招雷达-CSV模板.csv', csvTemplate(), 'text/csv;charset=utf-8')}><Download size={16}/>下载模板</Button><Button variant="secondary" onClick={() => csvRef.current?.click()}><Upload size={16}/>导入 CSV</Button><Button onClick={() => downloadText('秋招雷达-投递记录.csv', toCsv(records), 'text/csv;charset=utf-8')} disabled={!records.length}><FileDown size={16}/>导出 CSV</Button></> },
    { icon: FileJson, title: 'JSON 备份', desc: '保留完整状态变化历史，适合换浏览器前手动备份。', actions: <><Button variant="secondary" onClick={() => jsonRef.current?.click()}><FileUp size={16}/>恢复备份</Button><Button onClick={() => downloadText(`秋招雷达-备份-${new Date().toISOString().slice(0, 10)}.json`, createBackup(records))} disabled={!records.length}><Download size={16}/>下载备份</Button></> },
  ]
  return <div className="space-y-6 animate-rise"><div><p className="text-sm font-bold uppercase tracking-widest text-amber">数据与接入</p><h2 className="mt-1 text-2xl font-extrabold text-ink">你的数据，只由你掌握</h2><p className="mt-2 text-sm text-stone-500">全部数据保存在当前浏览器的 localStorage 中；清理浏览器数据前请先下载备份。</p></div>
    {message && <div className={`flex items-start gap-2 rounded-md border px-4 py-3 text-sm ${message.tone === 'ok' ? 'border-teal-200 bg-teal-50 text-teal-800' : 'border-red-200 bg-red-50 text-red-700'}`}>{message.tone === 'ok' ? <Database size={18}/> : <AlertTriangle size={18}/>}<span>{message.text}</span></div>}
    <div className="grid gap-5 lg:grid-cols-2">{sections.map(s => <Card key={s.title}><CardContent><div className="mb-4 grid size-10 place-items-center rounded-md bg-orange-50 text-amber"><s.icon size={20}/></div><h3 className="font-bold text-ink">{s.title}</h3><p className="mt-1 min-h-10 text-sm leading-6 text-stone-500">{s.desc}</p><div className="mt-5 flex flex-wrap gap-2">{s.actions}</div></CardContent></Card>)}</div>
    <Card><CardHeader><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-md bg-teal-50 text-teal"><Plug size={20}/></div><div><h3 className="font-bold text-ink">平台接入路线</h3><p className="mt-1 text-sm text-stone-500">当前是手动巡检 MVP，不是自动监控服务。</p></div></div></CardHeader><CardContent className="grid gap-5 lg:grid-cols-[1fr_auto]"><div><div className="mb-4 flex flex-wrap gap-2"><Badge tone="amber">尚未自动接入</Badge><Badge tone="teal">已预留 Adapter 接口</Badge></div><p className="text-sm leading-7 text-stone-600">本应用不会绕过平台登录、验证码或反爬策略，也不会在后台抓取招聘平台。后续将通过用户已登录的 <strong className="text-ink">Ego Lite 浏览器</strong>，为牛客、BOSS 直聘、字节、腾讯、阿里等平台逐个录制稳定、可审阅的巡检流程。</p><p className="mt-3 text-sm leading-7 text-stone-600">已预留 <code className="rounded bg-stone-100 px-1.5 py-0.5 text-xs">ConnectorAdapter</code> 与版本化 <code className="rounded bg-stone-100 px-1.5 py-0.5 text-xs">CheckResult</code> JSON 导入接口，自动化结果必须由用户主动导入。</p></div><Button variant="secondary" onClick={() => checkRef.current?.click()}><Bot size={16}/>导入检查结果</Button></CardContent></Card>
    <Card className="border-red-200"><CardContent className="flex flex-wrap items-center justify-between gap-4"><div className="flex gap-3"><LockKeyhole className="mt-0.5 shrink-0 text-red-600" size={20}/><div><h3 className="font-bold text-ink">清空本地数据</h3><p className="mt-1 text-sm text-stone-500">此操作会永久删除 {records.length} 条记录及历史，无法撤销。</p></div></div><Button variant="danger" onClick={() => setConfirmClear(true)} disabled={!records.length}><Trash2 size={16}/>清空全部</Button></CardContent></Card>
    <input ref={csvRef} hidden type="file" accept=".csv,text/csv" onChange={e => readFile(e.target.files?.[0], importCsv)}/><input ref={jsonRef} hidden type="file" accept=".json,application/json" onChange={e => readFile(e.target.files?.[0], restore)}/><input ref={checkRef} hidden type="file" accept=".json,application/json" onChange={e => readFile(e.target.files?.[0], importCheck)}/>
    <Dialog open={confirmClear} onClose={() => setConfirmClear(false)} title="确认清空全部数据？" description="记录和状态历史会一起删除，且无法撤销。"><div className="rounded-md border border-red-200 bg-red-50 p-4 text-sm leading-6 text-red-800">建议先下载 JSON 备份。若确定清空，请点击下方红色按钮再次确认。</div><div className="mt-5 flex justify-end gap-3"><Button variant="ghost" onClick={() => setConfirmClear(false)}>取消</Button><Button variant="danger" onClick={() => { onClear(); setConfirmClear(false); setMessage({ tone: 'ok', text: '本地数据已清空。' }) }}>确认永久清空</Button></div></Dialog>
  </div>
}
