import { Check, ExternalLink, Radio, RefreshCw } from 'lucide-react'
import { useMemo, useState } from 'react'
import { QUEUE_STAGES, alertLevel, formatDate, inspectionPriority, silentDays } from '../lib/radar'
import { STAGES, type ApplicationRecord, type Stage } from '../types'
import { Badge, Button } from './ui/Button'
import { Card, CardContent } from './ui/Card'
import { Dialog } from './ui/Dialog'
import { Field, Input, Select, Textarea } from './ui/Field'

export function InspectionQueue({ records, onNoChange, onUpdate }: { records: ApplicationRecord[]; onNoChange: (r: ApplicationRecord) => void; onUpdate: (r: ApplicationRecord, stage: Stage, note: string, appliedAt?: string) => void }) {
  const queue = useMemo(() => records.filter(r => QUEUE_STAGES.includes(r.stage)).sort((a, b) => inspectionPriority(b) - inspectionPriority(a)), [records])
  const [editing, setEditing] = useState<ApplicationRecord>(); const [stage, setStage] = useState<Stage>('已投递'); const [note, setNote] = useState(''); const [appliedAt, setAppliedAt] = useState(''); const [dateError, setDateError] = useState('')
  const startUpdate = (r: ApplicationRecord) => { setEditing(r); setStage(r.stage); setNote(''); setAppliedAt(r.appliedAt); setDateError('') }
  const saveUpdate = () => { if (!editing) return; if (stage !== '待投递' && !appliedAt) { setDateError('更新为已投递或后续阶段前，请补充投递日期'); return } onUpdate(editing, stage, note, appliedAt); setEditing(undefined) }
  return <div className="space-y-5 animate-rise">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-widest text-amber">巡检队列</p><h2 className="mt-1 text-2xl font-extrabold text-ink">先处理待投递，再检查沉默机会</h2><p className="mt-2 text-sm text-stone-500">待投递机会优先展示；已投递记录按未检查天数与阶段紧迫度排序。</p></div><Badge tone={queue.some(r => alertLevel(r) === '14天+') ? 'red' : 'teal'}>{queue.length} 条待处理</Badge></div>
    {!queue.length ? <Card className="grid min-h-72 place-items-center p-8 text-center"><div><div className="mx-auto mb-4 grid size-14 place-items-center rounded-full bg-teal-50 text-teal"><Check size={27}/></div><h3 className="text-lg font-bold text-ink">队列已经清空</h3><p className="mt-1 text-sm text-stone-500">新增待投递或进行中的机会后，会自动出现在这里。</p></div></Card> : <div className="grid gap-4">{queue.map((r, index) => { const level = alertLevel(r); const pending = level === '待投递'; return <Card key={r.id} className={index === 0 ? 'border-orange-300 shadow-float' : ''}><CardContent className="grid gap-4 p-4 sm:p-5 lg:grid-cols-[3rem_minmax(0,1fr)_auto] lg:items-center"><div className={`grid size-11 place-items-center rounded-md font-extrabold ${level === '14天+' ? 'bg-red-50 text-red-700' : level === '7天+' ? 'bg-orange-50 text-amber' : pending ? 'bg-violet-50 text-violet-700' : 'bg-stone-100 text-stone-500'}`}>{index + 1}</div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="font-bold text-ink">{r.company} · {r.role}</h3>{r.isSample && <Badge tone="blue">示例</Badge>}<Badge tone={level === '14天+' ? 'red' : level === '7天+' ? 'amber' : pending ? 'blue' : 'teal'}>{pending ? '等待投递' : level === '正常' ? '近期已检查' : `${silentDays(r)} 天无变化`}</Badge></div><div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-xs text-stone-500"><span>{r.platform}</span><span>当前：{r.stage}</span><span>{pending ? `投递日期：${formatDate(r.appliedAt, false, '待补充')}` : `上次检查：${formatDate(r.lastCheckedAt)}`}</span></div></div><div className="flex flex-wrap gap-2 lg:justify-end">{r.url ? <Button variant="secondary" onClick={() => window.open(r.url, '_blank', 'noopener,noreferrer')}><ExternalLink size={16}/>{pending ? '去投递' : '去检查'}</Button> : <Button variant="secondary" disabled title="请先补充投递链接"><ExternalLink size={16}/>无链接</Button>}{!pending && <Button variant="ghost" onClick={() => onNoChange(r)}><RefreshCw size={16}/>无变化</Button>}<Button onClick={() => startUpdate(r)}><Radio size={16}/>更新状态</Button></div></CardContent></Card>})}</div>}
    <Dialog open={!!editing} onClose={() => setEditing(undefined)} title="记录处理结果" description={editing ? `${editing.company} · ${editing.role}` : ''}><div className="space-y-4"><Field label="最新阶段"><Select value={stage} onChange={e => { setStage(e.target.value as Stage); setDateError('') }}>{STAGES.map(s => <option key={s}>{s}</option>)}</Select></Field>{stage !== '待投递' && <Field label="投递日期" required error={dateError}><Input type="date" value={appliedAt} onChange={e => { setAppliedAt(e.target.value); setDateError('') }} max={new Date().toISOString().slice(0, 10)} /></Field>}<Field label="检查备注"><Textarea value={note} onChange={e => setNote(e.target.value)} placeholder="例如：已完成投递，等待通知" /></Field><div className="flex justify-end gap-3 border-t border-stone-200 pt-4"><Button variant="ghost" onClick={() => setEditing(undefined)}>取消</Button><Button onClick={saveUpdate}>保存结果</Button></div></div></Dialog>
  </div>
}
